// GENERATED by scripts/release-keys.mjs — do not edit by hand.
//
// The Ed25519 public key releases are verified against. The matching private key
// lives offline; regenerate the pair (and re-release) if it is ever exposed.
//
// Absent or empty means this build cannot verify signatures, and the updater
// refuses to install anything rather than trusting an unverified download.
export const RELEASE_PUBLIC_KEY = "MCowBQYDK2VwAyEAjummp06F/W5nJsBOvDW6WeCTUjIE9B8vWiGBb4Xc5CM=";
