// 9Router's free-tier chat providers, expressed as routy data — generated by
// rigs/gen-free-tier-catalog.mjs from rigs/free-tier.json (9router/open-sse/providers/registry,
// category === "freeTier"). Regenerate, do not hand-edit.
//
// routy posts chat straight to `baseUrl` (core/routing.mjs: `url: ... node.baseUrl`) with a
// bearer Authorization header, so each supported baseUrl here is the FULL endpoint including
// /chat/completions. `supported: false` names the transport routy does not speak (a local TTS
// service, generateContent, Ollama's native wire, Vertex signing, OAuth) and carries no preset —
// an entry that looks addable and then fails would be worse than the gap.

export const FREE_TIER = Object.freeze(
  [
  {
    "id": "api-airforce",
    "name": "API.airforce",
    "baseUrl": "https://api.airforce/v1/chat/completions",
    "format": "openai",
    "models": [
      {
        "id": "gpt-oss-120b",
        "name": "GPT-OSS 120B (Free)"
      },
      {
        "id": "gpt-oss-20b",
        "name": "GPT-OSS 20B (Free)"
      },
      {
        "id": "kimi-k2.7-code",
        "name": "Kimi K2.7 Code (Free)"
      }
    ],
    "keyUrl": "https://api.airforce",
    "requires": [],
    "supported": true,
    "why": null
  },
  {
    "id": "bazaarlink",
    "name": "Bazaarlink",
    "baseUrl": "https://bazaarlink.ai/api/v1/chat/completions",
    "format": "openai",
    "models": [
      {
        "id": "auto:free",
        "name": "Auto Free (Zero Cost)"
      },
      {
        "id": "claude-opus-4.7",
        "name": "Claude Opus 4.7"
      },
      {
        "id": "claude-sonnet-4.6",
        "name": "Claude Sonnet 4.6"
      },
      {
        "id": "claude-haiku-4.5",
        "name": "Claude Haiku 4.5"
      },
      {
        "id": "gpt-5.5",
        "name": "GPT-5.5"
      },
      {
        "id": "gpt-5.4",
        "name": "GPT-5.4"
      },
      {
        "id": "gpt-5.4-mini",
        "name": "GPT-5.4 Mini"
      },
      {
        "id": "gpt-5.4-nano",
        "name": "GPT-5.4 Nano"
      },
      {
        "id": "grok-4.3",
        "name": "Grok 4.3"
      },
      {
        "id": "grok-4.20",
        "name": "Grok 4.20"
      },
      {
        "id": "gemini-3.1-pro-preview",
        "name": "Gemini 3.1 Pro"
      },
      {
        "id": "gemini-3-flash-preview",
        "name": "Gemini 3 Flash"
      },
      {
        "id": "gemini-3.1-flash-lite-preview",
        "name": "Gemini 3.1 Flash Lite"
      },
      {
        "id": "kimi-k2.6",
        "name": "Kimi K2.6"
      },
      {
        "id": "kimi-k2.5",
        "name": "Kimi K2.5"
      },
      {
        "id": "glm-5.1",
        "name": "GLM 5.1"
      },
      {
        "id": "glm-5",
        "name": "GLM 5"
      },
      {
        "id": "mimo-v2.5-pro",
        "name": "MiMo-V2.5-Pro"
      },
      {
        "id": "mimo-v2.5",
        "name": "MiMo-V2.5"
      },
      {
        "id": "minimax-m3",
        "name": "MiniMax M3"
      },
      {
        "id": "minimax-m2.7",
        "name": "MiniMax M2.7"
      },
      {
        "id": "minimax-m2.5",
        "name": "MiniMax M2.5"
      },
      {
        "id": "qwen3.6-plus",
        "name": "Qwen 3.6 Plus"
      },
      {
        "id": "nemotron-3-super-120b-a12b",
        "name": "Nemotron 3 Super"
      }
    ],
    "keyUrl": "https://bazaarlink.ai",
    "requires": [],
    "supported": true,
    "why": null
  },
  {
    "id": "byteplus",
    "name": "BytePlus ModelArk",
    "baseUrl": "https://ark.ap-southeast.bytepluses.com/api/coding/v3/chat/completions",
    "format": "openai",
    "models": [
      {
        "id": "seed-2-0-pro-260328",
        "name": "Seed 2.0 Pro"
      },
      {
        "id": "seed-2-0-code-preview-260328",
        "name": "Seed 2.0 Code Preview"
      },
      {
        "id": "seed-2-0-mini-260215",
        "name": "Seed 2.0 Mini"
      },
      {
        "id": "seed-2-0-lite-260228",
        "name": "Seed 2.0 Lite"
      },
      {
        "id": "kimi-k2-thinking-251104",
        "name": "Kimi K2 Thinking"
      },
      {
        "id": "glm-4-7-251222",
        "name": "GLM 4.7"
      },
      {
        "id": "gpt-oss-120b-250805",
        "name": "GPT-OSS-120B"
      }
    ],
    "keyUrl": "https://console.byteplus.com/ark/region:ark+ap-southeast-1/apiKey",
    "requires": [],
    "supported": true,
    "why": null
  },
  {
    "id": "cloudflare-ai",
    "name": "Cloudflare",
    "baseUrl": "https://api.cloudflare.com/client/v4/accounts/{accountId}/ai/v1/chat/completions",
    "format": "openai",
    "models": [
      {
        "id": "@cf/meta/llama-3.2-1b-instruct",
        "name": "Llama 3.2 1B Instruct"
      },
      {
        "id": "@cf/meta/llama-3.2-3b-instruct",
        "name": "Llama 3.2 3B Instruct"
      },
      {
        "id": "@cf/meta/llama-3.1-8b-instruct-fp8-fast",
        "name": "Llama 3.1 8B Instruct FP8 Fast"
      },
      {
        "id": "@cf/meta/llama-3.1-8b-instruct-awq",
        "name": "Llama 3.1 8B Instruct AWQ"
      },
      {
        "id": "@cf/mistralai/mistral-small-3.1-24b-instruct",
        "name": "Mistral Small 3.1 24B Instruct"
      },
      {
        "id": "@cf/meta/llama-3.1-70b-instruct-fp8-fast",
        "name": "Llama 3.1 70B Instruct FP8 Fast"
      },
      {
        "id": "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
        "name": "Llama 3.3 70B Instruct FP8 Fast"
      },
      {
        "id": "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b",
        "name": "DeepSeek R1 Distill Qwen 32B"
      },
      {
        "id": "@cf/moonshotai/kimi-k2.5",
        "name": "Kimi K2.5"
      },
      {
        "id": "@cf/moonshotai/kimi-k2.6",
        "name": "Kimi K2.6"
      },
      {
        "id": "@cf/zai-org/glm-4.7-flash",
        "name": "GLM 4.7 Flash"
      },
      {
        "id": "@cf/qwen/qwq-32b",
        "name": "QwQ 32B"
      },
      {
        "id": "@cf/qwen/qwen2.5-coder-32b-instruct",
        "name": "Qwen 2.5 Coder 32B Instruct"
      },
      {
        "id": "@cf/black-forest-labs/flux-2-klein-9b",
        "name": "FLUX.2 Klein 9B"
      },
      {
        "id": "@cf/black-forest-labs/flux-2-klein-4b",
        "name": "FLUX.2 Klein 4B"
      },
      {
        "id": "@cf/black-forest-labs/flux-2-dev",
        "name": "FLUX.2 Dev"
      },
      {
        "id": "@cf/leonardo/lucid-origin",
        "name": "Lucid Origin"
      },
      {
        "id": "@cf/leonardo/phoenix-1.0",
        "name": "Phoenix 1.0"
      },
      {
        "id": "@cf/black-forest-labs/flux-1-schnell",
        "name": "FLUX.1 Schnell"
      },
      {
        "id": "@cf/bytedance/stable-diffusion-xl-lightning",
        "name": "SDXL Lightning"
      },
      {
        "id": "@cf/lykon/dreamshaper-8-lcm",
        "name": "DreamShaper 8 LCM"
      },
      {
        "id": "@cf/runwayml/stable-diffusion-v1-5-img2img",
        "name": "Stable Diffusion v1.5 Img2Img"
      },
      {
        "id": "@cf/runwayml/stable-diffusion-v1-5-inpainting",
        "name": "Stable Diffusion v1.5 Inpainting"
      },
      {
        "id": "@cf/stabilityai/stable-diffusion-xl-base-1.0",
        "name": "SDXL Base 1.0"
      }
    ],
    "keyUrl": "https://dash.cloudflare.com/profile/api-tokens",
    "requires": [
      "replace {accountId} in the node's URL with your Cloudflare account id"
    ],
    "supported": true,
    "why": null
  },
  {
    "id": "coqui",
    "name": "Coqui TTS",
    "baseUrl": null,
    "format": "openai",
    "models": [],
    "keyUrl": "https://github.com/coqui-ai/TTS",
    "requires": [],
    "supported": false,
    "why": "a local TTS service — no chat endpoint exists (its own registry entry has no baseUrl)"
  },
  {
    "id": "edge-tts",
    "name": "Edge TTS",
    "baseUrl": null,
    "format": "openai",
    "models": [],
    "keyUrl": null,
    "requires": [],
    "supported": false,
    "why": "a local TTS service — no chat endpoint exists (its own registry entry has no baseUrl)"
  },
  {
    "id": "gemini",
    "name": "Gemini",
    "baseUrl": "https://generativelanguage.googleapis.com/v1beta/models",
    "format": "gemini",
    "models": [
      {
        "id": "gemini-3.8-flash",
        "name": "Gemini 3.8 Flash"
      },
      {
        "id": "gemini-3.7-flash",
        "name": "Gemini 3.7 Flash"
      },
      {
        "id": "gemini-3.6-flash",
        "name": "Gemini 3.6 Flash"
      },
      {
        "id": "gemini-3.5-flash-lite",
        "name": "Gemini 3.5 Flash Lite"
      },
      {
        "id": "gemini-3.1-pro-preview",
        "name": "Gemini 3.1 Pro Preview"
      },
      {
        "id": "gemini-3.1-flash-lite-preview",
        "name": "Gemini 3.1 Flash Lite Preview"
      },
      {
        "id": "gemini-3-flash-preview",
        "name": "Gemini 3 Flash Preview"
      },
      {
        "id": "gemini-2.5-pro",
        "name": "Gemini 2.5 Pro"
      },
      {
        "id": "gemini-2.5-flash",
        "name": "Gemini 2.5 Flash"
      },
      {
        "id": "gemini-2.5-flash-lite",
        "name": "Gemini 2.5 Flash Lite"
      },
      {
        "id": "gemma-4-31b-it",
        "name": "Gemma 4 31B IT"
      },
      {
        "id": "gemini-embedding-2-preview",
        "name": "Gemini Embedding 2 Preview"
      },
      {
        "id": "gemini-embedding-001",
        "name": "Gemini Embedding 001"
      },
      {
        "id": "text-embedding-005",
        "name": "Text Embedding 005"
      },
      {
        "id": "text-embedding-004",
        "name": "Text Embedding 004 (Legacy)"
      },
      {
        "id": "gemini-3.1-flash-image-preview",
        "name": "Gemini 3.1 Flash Image (Nano Banana 2)"
      },
      {
        "id": "gemini-3-pro-image-preview",
        "name": "Gemini 3 Pro Image (Nano Banana Pro)"
      },
      {
        "id": "gemini-2.5-flash-image",
        "name": "Gemini 2.5 Flash Image (Nano Banana)"
      },
      {
        "id": "gemini-2.5-pro",
        "name": "Gemini 2.5 Pro (Best)"
      },
      {
        "id": "gemini-2.5-flash",
        "name": "Gemini 2.5 Flash"
      },
      {
        "id": "gemini-2.5-flash-lite",
        "name": "Gemini 2.5 Flash Lite (Cheapest)"
      },
      {
        "id": "gemini-2.0-flash",
        "name": "Gemini 2.0 Flash"
      },
      {
        "id": "gemini-3.1-flash-tts-preview",
        "name": "Gemini 3.1 Flash TTS"
      },
      {
        "id": "gemini-2.5-flash-preview-tts",
        "name": "Gemini 2.5 Flash TTS"
      },
      {
        "id": "gemini-2.5-pro-preview-tts",
        "name": "Gemini 2.5 Pro TTS"
      },
      {
        "id": "embedding-001",
        "name": "Embedding 001"
      }
    ],
    "keyUrl": "https://aistudio.google.com/app/apikey",
    "requires": [],
    "supported": false,
    "why": "9Router speaks Google's generateContent format; routy's chat speaks OpenAI/Claude/Responses"
  },
  {
    "id": "google-tts",
    "name": "Google TTS",
    "baseUrl": null,
    "format": "openai",
    "models": [],
    "keyUrl": null,
    "requires": [],
    "supported": false,
    "why": "a local TTS service — no chat endpoint exists (its own registry entry has no baseUrl)"
  },
  {
    "id": "kilo-gateway",
    "name": "Kilo Gateway",
    "baseUrl": "https://api.kilo.ai/api/gateway/chat/completions",
    "format": "openai",
    "models": [
      {
        "id": "kilo-auto/free",
        "name": "Kilo Auto Free"
      },
      {
        "id": "nvidia/nemotron-3-super-120b-a12b:free",
        "name": "Nemotron 3 Super 120B (Free)"
      },
      {
        "id": "nvidia/nemotron-3-ultra-550b-a55b:free",
        "name": "Nemotron 3 Ultra 550B (Free)"
      },
      {
        "id": "kwaipilot/kat-coder-pro-v2.5:free",
        "name": "Kat Coder Pro v2.5 (Free)"
      },
      {
        "id": "kilo-auto/frontier",
        "name": "Kilo Auto Frontier"
      },
      {
        "id": "kilo-auto/balanced",
        "name": "Kilo Auto Balanced"
      }
    ],
    "keyUrl": "https://kilo.ai/dashboard?tab=apiKeys",
    "requires": [],
    "supported": true,
    "why": null
  },
  {
    "id": "kimchi",
    "name": "Kimchi",
    "baseUrl": "https://llm.kimchi.dev/openai/v1/chat/completions",
    "format": "openai",
    "models": [
      {
        "id": "minimax-m3",
        "name": "MiniMax-M3"
      },
      {
        "id": "kimi-k2.7",
        "name": "Kimi-K2.7"
      },
      {
        "id": "kimi-k2.6",
        "name": "Kimi-K2.6"
      },
      {
        "id": "kimi-k2.5",
        "name": "Kimi-K2.5"
      },
      {
        "id": "nemotron-3-ultra-fp4",
        "name": "Nemotron 3 Ultra FP4"
      },
      {
        "id": "minimax-m2.7",
        "name": "MiniMax-M2.7"
      },
      {
        "id": "claude-opus-4-6",
        "name": "Claude Opus 4.6"
      },
      {
        "id": "claude-sonnet-4-6",
        "name": "Claude Sonnet 4.6"
      }
    ],
    "keyUrl": "https://app.kimchi.dev",
    "requires": [],
    "supported": false,
    "why": "needs a 9Router OAuth login; routy has no OAuth flows"
  },
  {
    "id": "local-device",
    "name": "Local Device",
    "baseUrl": null,
    "format": "openai",
    "models": [],
    "keyUrl": null,
    "requires": [],
    "supported": false,
    "why": "runs on your device — no published endpoint (its own registry entry has no baseUrl)"
  },
  {
    "id": "nvidia",
    "name": "NVIDIA NIM",
    "baseUrl": "https://integrate.api.nvidia.com/v1/chat/completions",
    "format": "openai",
    "models": [
      {
        "id": "minimaxai/minimax-m2.7",
        "name": "MiniMax M2.7"
      },
      {
        "id": "minimaxai/minimax-m3",
        "name": "MiniMax M3"
      },
      {
        "id": "z-ai/glm-5.2",
        "name": "GLM 5.2"
      },
      {
        "id": "deepseek-ai/deepseek-v4-pro",
        "name": "DeepSeek V4 Pro"
      },
      {
        "id": "deepseek-ai/deepseek-v4-flash",
        "name": "DeepSeek V4 Flash"
      },
      {
        "id": "moonshotai/kimi-k2.6",
        "name": "Kimi K2.6"
      },
      {
        "id": "nvidia/nemotron-3-ultra-550b-a55b",
        "name": "Nemotron 3 Ultra"
      },
      {
        "id": "nvidia/nv-embedqa-e5-v5",
        "name": "NV EmbedQA E5 v5"
      },
      {
        "id": "nvidia/parakeet-ctc-1.1b-asr",
        "name": "Parakeet CTC 1.1B"
      },
      {
        "id": "fastpitch",
        "name": "FastPitch"
      },
      {
        "id": "tacotron2",
        "name": "Tacotron2"
      }
    ],
    "keyUrl": "https://build.nvidia.com/settings/api-keys",
    "requires": [],
    "supported": true,
    "why": null
  },
  {
    "id": "ollama",
    "name": "Ollama Cloud",
    "baseUrl": "https://ollama.com/api/chat",
    "format": "ollama",
    "models": [
      {
        "id": "gpt-oss:120b",
        "name": "GPT OSS 120B"
      },
      {
        "id": "kimi-k2.5",
        "name": "Kimi K2.5"
      },
      {
        "id": "glm-5",
        "name": "GLM 5"
      },
      {
        "id": "minimax-m2.5",
        "name": "MiniMax M2.5"
      },
      {
        "id": "glm-4.7-flash",
        "name": "GLM 4.7 Flash"
      },
      {
        "id": "qwen3.5",
        "name": "Qwen3.5"
      },
      {
        "id": "minimax-m3",
        "name": "MiniMax M3"
      }
    ],
    "keyUrl": "https://ollama.com/settings/keys",
    "requires": [],
    "supported": false,
    "why": "9Router speaks Ollama's native /api/chat wire; routy's chat speaks OpenAI/Claude/Responses"
  },
  {
    "id": "openrouter",
    "name": "OpenRouter",
    "baseUrl": "https://openrouter.ai/api/v1/chat/completions",
    "format": "openai",
    "models": [
      {
        "id": "openai/text-embedding-3-large",
        "name": "OpenAI Text Embedding 3 Large"
      },
      {
        "id": "openai/text-embedding-3-small",
        "name": "OpenAI Text Embedding 3 Small"
      },
      {
        "id": "openai/text-embedding-ada-002",
        "name": "OpenAI Text Embedding Ada 002"
      },
      {
        "id": "qwen/qwen3-embedding-8b",
        "name": "Qwen3 Embedding 8B"
      },
      {
        "id": "perplexity/pplx-embed-v1-4b",
        "name": "Perplexity Embed V1 4B"
      },
      {
        "id": "perplexity/pplx-embed-v1-0.6b",
        "name": "Perplexity Embed V1 0.6B"
      },
      {
        "id": "nvidia/llama-nemotron-embed-vl-1b-v2:free",
        "name": "NVIDIA Nemotron Embed VL 1B V2 (Free)"
      },
      {
        "id": "openai/gpt-4o-mini-tts",
        "name": "GPT-4o Mini TTS"
      },
      {
        "id": "openai/tts-1-hd",
        "name": "TTS-1 HD"
      },
      {
        "id": "openai/tts-1",
        "name": "TTS-1"
      },
      {
        "id": "openai/dall-e-3",
        "name": "DALL-E 3 (via OpenRouter)"
      },
      {
        "id": "openai/gpt-image-1",
        "name": "GPT Image 1 (via OpenRouter)"
      },
      {
        "id": "google/imagen-3.0-generate-002",
        "name": "Imagen 3 (via OpenRouter)"
      },
      {
        "id": "black-forest-labs/FLUX.1-schnell",
        "name": "FLUX.1 Schnell (via OpenRouter)"
      },
      {
        "id": "google/veo-3.1",
        "name": "Veo 3.1 (via OpenRouter)"
      },
      {
        "id": "openai/sora-2-pro",
        "name": "Sora 2 Pro (via OpenRouter)"
      },
      {
        "id": "bytedance/seedance-2.0",
        "name": "Seedance 2.0 (via OpenRouter)"
      }
    ],
    "keyUrl": "https://openrouter.ai/settings/keys",
    "requires": [],
    "supported": true,
    "why": null
  },
  {
    "id": "poolside",
    "name": "Poolside",
    "baseUrl": "https://inference.poolside.ai/v1/chat/completions",
    "format": "openai",
    "models": [
      {
        "id": "poolside/laguna-s-2.1",
        "name": "Laguna S 2.1"
      },
      {
        "id": "poolside/laguna-xs-2.1",
        "name": "Laguna XS 2.1"
      }
    ],
    "keyUrl": "https://platform.poolside.ai/api-keys",
    "requires": [],
    "supported": true,
    "why": null
  },
  {
    "id": "searxng",
    "name": "SearXNG",
    "baseUrl": null,
    "format": "openai",
    "models": [],
    "keyUrl": "https://docs.searxng.org",
    "requires": [],
    "supported": false,
    "why": "a search engine you host yourself — no endpoint in the registry"
  },
  {
    "id": "tortoise",
    "name": "Tortoise TTS",
    "baseUrl": null,
    "format": "openai",
    "models": [],
    "keyUrl": "https://github.com/neonbjb/tortoise-tts",
    "requires": [],
    "supported": false,
    "why": "a local TTS service — no chat endpoint exists (its own registry entry has no baseUrl)"
  },
  {
    "id": "vertex",
    "name": "Vertex AI",
    "baseUrl": "https://aiplatform.googleapis.com",
    "format": "vertex",
    "models": [
      {
        "id": "gemini-3.1-pro-preview",
        "name": "Gemini 3.1 Pro Preview"
      },
      {
        "id": "gemini-3.1-flash-lite-preview",
        "name": "Gemini 3.1 Flash Lite Preview"
      },
      {
        "id": "gemini-3-flash-preview",
        "name": "Gemini 3 Flash Preview"
      },
      {
        "id": "gemini-2.5-flash",
        "name": "Gemini 2.5 Flash"
      },
      {
        "id": "veo-3.1-generate-preview",
        "name": "Veo 3.1 (Preview)"
      },
      {
        "id": "veo-3.1-fast-generate-preview",
        "name": "Veo 3.1 Fast (Preview)"
      },
      {
        "id": "veo-3.0-generate-001",
        "name": "Veo 3"
      },
      {
        "id": "veo-2.0-generate-001",
        "name": "Veo 2"
      }
    ],
    "keyUrl": "https://console.cloud.google.com/iam-admin/serviceaccounts",
    "requires": [],
    "supported": false,
    "why": "9Router signs Vertex requests its own way; routy's chat speaks OpenAI/Claude/Responses"
  }
].map((e) => Object.freeze({ ...e, models: Object.freeze(e.models), requires: Object.freeze(e.requires) })),
);
