// Release signing keys — generate the pair, embed the public half.
//
//   node scripts/release-keys.mjs generate [--out <path>]
//   node scripts/release-keys.mjs show
//
// The gateway ships the PUBLIC key and refuses any release whose signature does not
// verify against it. That is what makes a 1-click updater defensible: without it, an
// attacker who takes over the GitHub account can sign a release that every install
// will happily download and execute.
//
// The PRIVATE key never belongs in the repository. It is written outside the tree by
// default and is meant to be moved to offline storage (a password manager, a USB key)
// and deleted from disk. If it leaks, the whole scheme is worthless — regenerate.
import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, "..");
const PUBKEY_MODULE = path.join(repo, "routy-core", "lib", "release-pubkey.mjs");
const DEFAULT_KEY_PATH = path.join(os.homedir(), ".routy", "release-signing.key");

const argv = process.argv.slice(2);
const cmd = argv[0] || "show";
const outFlag = argv.indexOf("--out");
const keyPath = outFlag >= 0 ? path.resolve(argv[outFlag + 1]) : DEFAULT_KEY_PATH;

const b64 = (key, type) => key.export({ type, format: "der" }).toString("base64");

function writePubkeyModule(spki) {
  fs.writeFileSync(
    PUBKEY_MODULE,
    `// GENERATED by scripts/release-keys.mjs — do not edit by hand.
//
// The Ed25519 public key releases are verified against. The matching private key
// lives offline; regenerate the pair (and re-release) if it is ever exposed.
//
// Absent or empty means this build cannot verify signatures, and the updater
// refuses to install anything rather than trusting an unverified download.
export const RELEASE_PUBLIC_KEY = ${JSON.stringify(spki)};
`,
  );
}

function generate() {
  const { publicKey, privateKey } = crypto.generateKeyPairSync("ed25519");
  const spki = b64(publicKey, "spki");
  const pkcs8 = b64(privateKey, "pkcs8");

  fs.mkdirSync(path.dirname(keyPath), { recursive: true });
  fs.writeFileSync(keyPath, `${pkcs8}\n`, { mode: 0o600 });
  writePubkeyModule(spki);

  console.log(`private key  ${keyPath}`);
  console.log(`public key   ${path.relative(repo, PUBKEY_MODULE)}  (committed)`);
  console.log("");
  console.log("Move the private key to offline storage and delete the local copy:");
  console.log(`  · store it in a password manager or on a USB key`);
  console.log(`  · then: rm "${keyPath}"`);
  console.log("Anyone holding it can sign a release every install will accept.");
}

function show() {
  const existing = fs.existsSync(keyPath) ? keyPath : null;
  console.log(`private key   ${existing ?? `${keyPath} (absent)`}`);
  const mod = fs.readFileSync(PUBKEY_MODULE, "utf8");
  const match = mod.match(/RELEASE_PUBLIC_KEY = "([^"]*)"/);
  const spki = match?.[1] ?? "";
  console.log(`public key    ${spki ? `${spki.slice(0, 16)}… (${spki.length} chars)` : "(not set — the updater will refuse to install)"}`);
  if (!existing) console.log("\nNo private key here — releases cannot be signed until one is generated or restored.");
}

if (cmd === "generate") generate();
else if (cmd === "show") show();
else {
  console.error(`unknown command: ${cmd}\n  usage: release-keys.mjs [generate|show] [--out <path>]`);
  process.exit(1);
}
